(require 'init-tree-sitter)
(require 'init-eglot)
(require 'init-data)
(require 'init-docker)
;; (require 'init-c)
;; (require 'init-elixir)
(require 'init-markdown)
(require 'init-nix)
(require 'init-python)
(require 'init-ruby)
(require 'init-web)
(require 'init-yaml)

(provide 'init-programming)
