(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

(require 'lisp-alfred)
(require 'lisp-buffer)
(require 'lisp-embark)
(require 'lisp-eww)
(require 'lisp-exercism)
(require 'lisp-file)
(require 'lisp-git)
(require 'lisp-kagi)
(require 'lisp-macos)
(require 'lisp-mail)
(require 'lisp-org)
(require 'lisp-project)

(provide 'init-lisp)
