(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(require 'init-elpa)

(setq custom-file (locate-user-emacs-file "custom.el"))
(require 'init-better-defaults)
(require 'init-macos-keybindings)
(require 'init-editing-utils)
(require 'init-gui-frames)
(require 'init-mode-line)
(require 'init-themes)
(require 'init-fonts)
(require 'init-minibuffer)
(require 'init-corfu)
(require 'init-git)
(require 'init-nix)
(require 'init-elixir)
(require 'init-denote)
(require 'init-org)
