(defun yejun/find-file-in-project (&optional dir)
  (interactive)
  (let ((project (project-current nil dir)))
    (project-find-file-in nil nil project)))

(defun yejun/search-project (&optional dir thing)
  (interactive)
  (let* ((project (project-current nil dir))
         (root-dir (project-root project)))
    (consult-ripgrep root-dir (when thing (thing-at-point thing)))))

(defun yejun/search-project-for-symbol-at-point ()
  (interactive)
  (yejun/search-project nil 'symbol))

(defun yejun/search-buffer (&optional thing)
  (interactive)
  (consult-line (when thing (thing-at-point thing))))

(defun yejun/search-buffer-for-symbol-at-point ()
  (interactive)
  (yejun/search-buffer 'symbol))

(defun yejun/yank-file-path ()
  (interactive)
  (when-let* ((filename (buffer-file-name))
              (path (abbreviate-file-name filename)))
    (kill-new path)
    (message "Copied path: %s" path)))

(defun yejun/yank-file-path-relative-to-project ()
  (interactive)
  (when-let* ((filename (buffer-file-name))
              (project (project-current))
              (root-dir (project-root project))
              (path (file-relative-name filename root-dir)))
    (kill-new path)
    (message "Copied path: %s" path)))

(provide 'init-lib)
